### PR TITLE
Fix ci and fmt

### LINKED ISSUE #64: Broken CI script
https://travis-ci.org/finalfusion/finalfrontier/jobs/590369304#L562-L565

```
+'[' '!' rustc --version
+grep '^rustc 1.31.0' ']'
ci/script.sh: line 9: [: missing `]'
grep: ]: No such file or directory
```

Also, while we're at it, we might want to move `cargo fmt` to the beginning of the script to get builds to fail sooner.

### PR DESCRIPTION
**Pull request by sebpuetz**
Fixes #64 and addresses the issues that got through CI.

### CODE REVIEW

File: ci/script.sh [hunk 1]
```diff
@@ -6,7 +6,7 @@ cargo build --target ${TARGET}
 cargo test --target ${TARGET}
 
 # On Rust 1.31.0, we only care about passing tests.
-if [ ! rustc --version | grep "^rustc 1.31.0" ]; then
+if [[ ! $(rustc --version | grep "^rustc 1.31.0") ]]; then
```
Comment (danieldk) [inline ci/script.sh]: Change this to:

```
if [ "$TRAVIS_RUST_VERSION" = "stable" ]; then
```

Btw: `[[` is a bash-ism. Of course, we have a bash she-bang, but it does makes scripts less portable.

**Comment by sebpuetz** [comment]
Builds are actually fixed now and the CI script doesn't use `[[ ]]` anymore

**Comment by sebpuetz** [comment]
> Could you squash the commits before merging?

Sure
